services:
  web:
    build: ./app
    container_name: scrutin_web
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASS: ${ADMIN_PASS:-password}
    volumes:
      - app:/var/www/html
    restart: unless-stopped

  db:
    image: mysql:latest
    container_name: scrutin_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: scrutin_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data:
  app:
